workflows:
  android-workflow:
    name: Android Kotlin Compose
    max_build_duration: 60
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
